#pragma once

#include <stm32wbxx.h>
#include <stm32wbxx_ll_gpio.h>
#include <stm32wbxx_ll_spi.h>

#define BOOT_BUTTON_BACK_GPIO_Port GPIOC
#define BOOT_BUTTON_BACK_Pin LL_GPIO_PIN_13
#define BOOT_BUTTON_DOWN_GPIO_Port GPIOC
#define BOOT_BUTTON_DOWN_Pin LL_GPIO_PIN_6
#define BOOT_BUTTON_LEFT_GPIO_Port GPIOB
#define BOOT_BUTTON_LEFT_Pin LL_GPIO_PIN_11
#define BOOT_BUTTON_OK_GPIO_Port GPIOH
#define BOOT_BUTTON_OK_Pin LL_GPIO_PIN_3
#define BOOT_BUTTON_RIGHT_GPIO_Port GPIOB
#define BOOT_BUTTON_RIGHT_Pin LL_GPIO_PIN_12
#define BOOT_BUTTON_UP_GPIO_Port GPIOB
#define BOOT_BUTTON_UP_Pin LL_GPIO_PIN_10

#define BOOT_CC1101_CS_GPIO_Port GPIOD
#define BOOT_CC1101_CS_Pin LL_GPIO_PIN_0
#define BOOT_CC1101_G0_GPIO_Port GPIOA
#define BOOT_CC1101_G0_Pin LL_GPIO_PIN_1

#define BOOT_DISPLAY_CS_GPIO_Port GPIOC
#define BOOT_DISPLAY_CS_Pin LL_GPIO_PIN_11
#define BOOT_DISPLAY_DI_GPIO_Port GPIOB
#define BOOT_DISPLAY_DI_Pin LL_GPIO_PIN_1
#define BOOT_DISPLAY_RST_GPIO_Port GPIOB
#define BOOT_DISPLAY_RST_Pin LL_GPIO_PIN_0

#define BOOT_IR_RX_GPIO_Port GPIOA
#define BOOT_IR_RX_Pin LL_GPIO_PIN_0
#define BOOT_IR_TX_GPIO_Port GPIOB
#define BOOT_IR_TX_Pin LL_GPIO_PIN_9

#define BOOT_NFC_CS_GPIO_Port GPIOE
#define BOOT_NFC_CS_Pin LL_GPIO_PIN_4

#define BOOT_PA4_GPIO_Port GPIOA
#define BOOT_PA4_Pin LL_GPIO_PIN_4
#define BOOT_PA6_GPIO_Port GPIOA
#define BOOT_PA6_Pin LL_GPIO_PIN_6
#define BOOT_PA7_GPIO_Port GPIOA
#define BOOT_PA7_Pin LL_GPIO_PIN_7
#define BOOT_PB2_GPIO_Port GPIOB
#define BOOT_PB2_Pin LL_GPIO_PIN_2
#define BOOT_PB3_GPIO_Port GPIOB
#define BOOT_PB3_Pin LL_GPIO_PIN_3
#define BOOT_PC0_GPIO_Port GPIOC
#define BOOT_PC0_Pin LL_GPIO_PIN_0
#define BOOT_PC1_GPIO_Port GPIOC
#define BOOT_PC1_Pin LL_GPIO_PIN_1
#define BOOT_PC3_GPIO_Port GPIOC
#define BOOT_PC3_Pin LL_GPIO_PIN_3

#define BOOT_PERIPH_POWER_GPIO_Port GPIOA
#define BOOT_PERIPH_POWER_Pin LL_GPIO_PIN_3

#define BOOT_QUARTZ_32MHZ_IN_GPIO_Port GPIOC
#define BOOT_QUARTZ_32MHZ_IN_Pin LL_GPIO_PIN_14
#define BOOT_QUARTZ_32MHZ_OUT_GPIO_Port GPIOC
#define BOOT_QUARTZ_32MHZ_OUT_Pin LL_GPIO_PIN_15

#define BOOT_RFID_OUT_GPIO_Port GPIOB
#define BOOT_RFID_OUT_Pin LL_GPIO_PIN_13
#define BOOT_RFID_PULL_GPIO_Port GPIOA
#define BOOT_RFID_PULL_Pin LL_GPIO_PIN_2
#define BOOT_RFID_RF_IN_GPIO_Port GPIOC
#define BOOT_RFID_RF_IN_Pin LL_GPIO_PIN_5
#define BOOT_RFID_TUNE_GPIO_Port GPIOA
#define BOOT_RFID_TUNE_Pin LL_GPIO_PIN_8

#define BOOT_RF_SW_0_GPIO_Port GPIOC
#define BOOT_RF_SW_0_Pin LL_GPIO_PIN_4

#define BOOT_SD_CD_GPIO_Port GPIOC
#define BOOT_SD_CD_Pin LL_GPIO_PIN_10
#define BOOT_SD_CS_GPIO_Port GPIOC
#define BOOT_SD_CS_Pin LL_GPIO_PIN_12

#define BOOT_SPEAKER_GPIO_Port GPIOB
#define BOOT_SPEAKER_Pin LL_GPIO_PIN_8

#define BOOT_VIBRO_GPIO_Port GPIOA
#define BOOT_VIBRO_Pin LL_GPIO_PIN_15

#define BOOT_iBTN_GPIO_Port GPIOB
#define BOOT_iBTN_Pin LL_GPIO_PIN_14

#define BOOT_USART1_TX_Pin LL_GPIO_PIN_6
#define BOOT_USART1_TX_Port GPIOB
#define BOOT_USART1_RX_Pin LL_GPIO_PIN_7
#define BOOT_USART1_RX_Port GPIOB

#define BOOT_SPI_D_MISO_GPIO_Port GPIOC
#define BOOT_SPI_D_MISO_Pin LL_GPIO_PIN_2
#define BOOT_SPI_D_MOSI_GPIO_Port GPIOB
#define BOOT_SPI_D_MOSI_Pin LL_GPIO_PIN_15
#define BOOT_SPI_D_SCK_GPIO_Port GPIOD
#define BOOT_SPI_D_SCK_Pin LL_GPIO_PIN_1

#define BOOT_SPI_R_MISO_GPIO_Port GPIOB
#define BOOT_SPI_R_MISO_Pin LL_GPIO_PIN_4
#define BOOT_SPI_R_MOSI_GPIO_Port GPIOB
#define BOOT_SPI_R_MOSI_Pin LL_GPIO_PIN_5
#define BOOT_SPI_R_SCK_GPIO_Port GPIOA
#define BOOT_SPI_R_SCK_Pin LL_GPIO_PIN_5
